slate-movte/slate-back

.github/actions/discord_action/action.yml
- discord 알림에 대한 버그 수정 시도
- 필요없는 코드 제거
Closes #1, #3
=> Bug : discord 알림

src/main/java/com/movte/slate/domain/user/domain/User.java
-  유저 인증 / 인가 JPA Entity 클래스 생성
=> feat(#5): 유저 인증 / 인가 JPA Entity 클래스 생성

.github/workflows/devcd.yml
- ec2에서 self-hosted runner가 yaml 설정 파일에 맞추어 cd작업 처리
- application-dev.yml 설정등은 진행 되지 않음(추후 진행 예정)
- 현재 잘 되는지 테스트용도.
- 세부 설명
- 세부 설명
=> Feat(#9): dev 서버 자동 배포를 위한 action.yaml 초안 작성

.github/workflows/devci.yml, .gitignore, build.gradle, docker_compose_local/docker-compose.yml, src/main/resources/application.yml, start.sh, stop.sh
- docker-compose를 사용해서 로컬 환경을 세팅하도록 한다
- docker-compose와 application.yml이 env 설정을 공유하도록 한다
- shell script를 활용해서 docker compose를 쉽게 사용하도록 함
Closes #18
=> Feat(#18): 로컬 환경 설정

src/main/java/com/movte/slate/aop/ControllerInputOutputLogger.java
Closes: #15
- 모든 Controller에 들어오는 Input(Parameter)와 모든 Controller에서 나가는 Output(returnObj)를 로그로 콘솔에 출력하는 기능 구현
=> Feat(#15): AOP를 사용한 Controller Input, Output 로그 출력 기능 구현

src/main/java/com/movte/slate/domain/user/api/UserInfoApi.java, src/main/java/com/movte/slate/domain/user/application/service/UserService.java, src/main/java/com/movte/slate/domain/user/application/service/dto/UserDto.java, src/main/java/com/movte/slate/oidc/JwtAuthenticationFilter.java
- "/user/info" API 기능 구현
- jwtTokenFactory.create 메소드에서 기간이 만료시 Exception 처리 로직 필요
- #30
=> feat: 유저 정보 조회 구현

src/main/java/com/movte/slate/domain/movie/domain/FilmLocation.java
- sidoCode, gugunCode 수정
- 세부 설명
- 세부 설명
=> Feat(#38): film_location 엔티티 구성 수정 

build.gradle, src/main/java/com/movte/slate/domain/auth/api/AuthApi.java, src/main/java/com/movte/slate/domain/user/api/LoginApi.java, src/main/java/com/movte/slate/domain/user/application/service/KakaoService.java, src/main/java/com/movte/slate/domain/user/application/service/LoginService.java, src/main/java/com/movte/slate/domain/user/application/usecase/LoginUsecase.java, src/main/java/com/movte/slate/domain/user/domain/OAuthType.java, src/main/java/com/movte/slate/domain/user/dto/OIDCPublicKeyDTO.java, src/main/java/com/movte/slate/domain/user/dto/TokenReponseDTO.java, src/main/java/com/movte/slate/domain/user/dto/TokenResponseDTO.java, src/main/java/com/movte/slate/global/annotation/UseCase.java
=> feat: oidc 카카오 서비스 구현

src/main/java/com/movte/slate/domain/movie/domain/StillCut.java
- stillcut entity 수정
- 세부 설명
- 세부 설명
=> Feat(#41): stillcut 수정 완료

src/main/resources/application.yml
[BUGFIX] Github Actions 빌드 과정 중에 테스트 실패하는 버그 해결
추가한 모든 환경 변수의 앞에 DEV_ prefix 추가
환경 변수의 앞에 DEV_ prefix가 붙어야 빌드 과정 중에 import됨
=> hotfix(#45):Github Actions 빌드 과정 중에 테스트 실패하는 버그 해결

.github/workflows/devcd.yml, .github/workflows/devci.yml
- ci,cd 과정에서 생기는 문제를 명확하게 판별하기 위해 -i option을 추가한다
=> Fix(#47): build시에 원인이 명확하게 드러나도록 수정

.github/workflows/devcd.yml, .github/workflows/devci.yml, src/main/java/com/movte/slate/domain/movie/domain/MovieActor.java, src/main/resources/application.yml
- ci, cd 과정에서 DEV_ prefix를 제거하도록 수정한다
=> Hotfix(#51): yml 및 ci 수정 

src/main/resources/application.yml
- example-1 기능 추가
- example-2 기능 추가
- 세부 설명
- 세부 설명
=> Fix(#53): SSL 설정 false로

src/main/resources/application.yml
Closes #55 
- example-1 기능 추가
- example-2 기능 추가
- 세부 설명
- 세부 설명
=> fix(#55): yml 수정

src/main/java/com/movte/slate/domain/movie/application/service/dto/MovieResponseDto.java, src/main/java/com/movte/slate/domain/movie/repository/FindMovieByTitlePort.java, src/main/java/com/movte/slate/domain/movie/repository/MovieJpaAdapter.java, src/main/java/com/movte/slate/domain/movie/repository/MovieRepository.java, src/main/java/com/movte/slate/domain/snapshot/application/service/SnapShotService.java, src/main/java/com/movte/slate/domain/snapshot/application/service/dto/SnapShotResponseDto.java, src/main/java/com/movte/slate/domain/snapshot/domain/Scene.java, src/main/java/com/movte/slate/domain/snapshot/repository/FindSceneByIdPort.java, src/main/java/com/movte/slate/domain/snapshot/repository/FindSceneByMoviePort.java, src/main/java/com/movte/slate/domain/snapshot/repository/SceneJpaAdapter.java, src/main/java/com/movte/slate/domain/snapshot/repository/SceneRepository.java, src/main/java/com/movte/slate/domain/snapshot/repository/SnapShotRepository.java, src/main/java/com/movte/slate/domain/stillcut/api/StillCutApi.java, src/main/java/com/movte/slate/domain/stillcut/application/service/SearchMovieTitleService.java, src/main/java/com/movte/slate/domain/stillcut/application/service/response/SearchMovieTitleServiceResponse.java, src/main/java/com/movte/slate/domain/stillcut/domain/StillCut.java, src/main/java/com/movte/slate/file/SaveSnapShotPort.java
=> Feat(#61) : 영화 타이틀로 씬 조회

src/main/java/com/movte/slate/domain/stillcut/api/StillCutApi.java, src/main/java/com/movte/slate/domain/stillcut/application/service/SearchUserIdService.java, src/main/java/com/movte/slate/domain/stillcut/application/service/dto/StillCutResponseDto.java, src/main/java/com/movte/slate/domain/stillcut/application/service/response/SearchUserIdServiceResponse.java, src/main/java/com/movte/slate/domain/stillcut/repository/FindStillCutByUserPort.java, src/main/java/com/movte/slate/domain/stillcut/repository/StillCutJpaAdapter.java, src/main/java/com/movte/slate/domain/stillcut/repository/StillCutRespository.java
/stillcut/finduser?id={유저아이디} API 기능 구현
Refs: #63
=> Feat(#63): 유저별 스틸 컷 조회 기능 구현

src/main/java/com/movte/slate/community/domain/Comment.java, src/main/java/com/movte/slate/community/domain/Feed.java, src/main/java/com/movte/slate/community/domain/Follow.java, src/main/java/com/movte/slate/community/domain/Like.java
feat: 커뮤니티 관련 Entity 설계
- Follow, Comment, Feed와 같은 Entity 클래스 만듦.
Refs: #65
=> feat: 커뮤니티 관련 Entity 설계

src/main/java/com/movte/slate/domain/attraction/domain/Attraction.java, src/main/java/com/movte/slate/domain/common/BaseTimeEntity.java, src/main/java/com/movte/slate/domain/user/domain/User.java
=> feat: basetimeentity 추가

src/main/java/com/movte/slate/domain/snapshot/domain/Scene.java
씬에 씬 장소 이름 추가
sceneDescription : 씬 장소 이름
=> feat: Scene Domain에 sceneDescription 추가

.github/workflows/prodcd.yml, .github/workflows/prodci.yml, src/main/resources/application.yml
- secret key 추가
- ec2 생성
- rds 생성
- production yml 작성
- 세부 설명
=> feat: production 서버용 파이프라인 작성

.github/workflows/prodcd.yml
Closes #84 
- example-1 기능 추가
- example-2 기능 추가
- 세부 설명
- 세부 설명
=> fix: action 이름 변경

src/main/java/com/movte/slate/domain/attraction/application/usecase/IntegrationSearchUseCase.java, src/main/java/com/movte/slate/domain/attraction/dto/response/MovieListResponseDto.java, src/main/java/com/movte/slate/domain/attraction/repository/AttractionRepository.java, src/main/java/com/movte/slate/domain/movie/domain/MovieActor.java, src/main/java/com/movte/slate/domain/movie/dto/MovieDetailResponseDto.java, src/main/java/com/movte/slate/domain/movie/repository/MovieQueryRepositoryImpl.java
- 출연진 주연만 검색되게 수정
- movie_actor에 role_order을 추가했습니다.
- 데이터 전처리시 주연을 1을 두고 기본값 0. 조연을 2로 햇는데 시간 관계상 조연의 데이터 정합성은 조금 부족합니다
- 1번은 확실하게 처리했기에 이걸로 처리하면 될거같습니다
-통합 검색 결과 5개 로 변경했습니다(클라 요구사항)
Closes #89
=> Feat(89): 배우 주연만 검색되게 수정, 통합검색 결과 5개로 변경

src/main/java/com/movte/slate/domain/snapshot/api/SceneApi.java, src/main/java/com/movte/slate/domain/snapshot/application/service/SceneService.java, src/main/java/com/movte/slate/domain/snapshot/application/service/request/InsertSceneServiceRequest.java, src/main/java/com/movte/slate/domain/snapshot/application/service/response/InsertSceneServiceResponse.java, src/main/java/com/movte/slate/domain/snapshot/domain/Scene.java, src/main/java/com/movte/slate/domain/snapshot/repository/FilmLocationJpaAdapter.java, src/main/java/com/movte/slate/domain/snapshot/repository/FilmLocationRepository.java, src/main/java/com/movte/slate/domain/snapshot/repository/SaveFilmLocationPort.java, src/main/java/com/movte/slate/domain/snapshot/repository/SaveImagePort.java, src/main/java/com/movte/slate/domain/snapshot/repository/SaveScenePort.java, src/main/java/com/movte/slate/domain/snapshot/repository/SceneJpaAdapter.java, src/main/java/com/movte/slate/file/S3Adapter.java, src/main/java/com/movte/slate/global/exception/BadRequestExceptionCode.java, src/main/resources/application.yml
`/scene/new` API
Body
address(주소), sidoCode(시도), gugunCode(구군), latitude(위도), longitude(경도), movieTitle(영화 타이틀), image(이미지), sceneLocation(씬 촬영 장소)
위와 같이 요청시 씬 추가
BadRequestExceptionCode에 012번 추가 완료
```
NO_MOVIE("012","영화가 존재하지 않습니다")
```
=> Feat(#78) : 씬 추가하는 API 개발 완료(개발용)
